version: '3.4'

services:
  apigeo.geodecodificador:
    image: ${DOCKER_REGISTRY-}apigeogeodecodificador
    build:
      context: .
      dockerfile: ApiGeo.geodecodificador/Dockerfile
    depends_on:
      - rabbitmq
    ports:
      - '5001:80'
      - '5002:443'
  apigeo.geolocalizador:
    image: ${DOCKER_REGISTRY-}apigeogeolocalizador
    build:
      context: .
      dockerfile: apiGeo.geolocalizador/Dockerfile
    depends_on:
      - rabbitmq
      - mongodb
    ports:
      - '5003:80'
      - '5004:443'
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '15672:15672'
      - '5672:5672'
  mongodb:
    image: mongo
    ports:
        - '27889:27017'